name: Nova Notificacao
description: Criar uma nova notificacao para os aplicativos
title: "[NOTIF] "
labels: ["active"]
body:
  - type: dropdown
    id: app_target
    attributes:
      label: Aplicativo Alvo
      description: Para qual aplicativo eh esta notificacao?
      options:
        - Mobile
        - Desktop  
        - Todos
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      options:
        - Informativo
        - Urgente
        - Manutencao
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Titulo da Notificacao
      placeholder: Ex. Nova versao disponivel
    validations:
      required: true

  - type: textarea
    id: message
    attributes:
      label: Mensagem
      description: Conteudo da notificacao
      placeholder: Descreva a notificacao...
    validations:
      required: true
